sudo: false
language: node_js

matrix:
  include:
  - node_js: 6
    env:
      - SAUCE=false
      - CXX=g++-4.8

# Make sure we have new NPM.
before_install:
  - npm install -g npm

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install wrtc
  - npm install leveldown
  - npm rebuild wrtc
  - npm rebuild leveldown

script:
  - npm test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
